name: DeadSouls
version: '1.21.3'
main: net.sanctuaryhosting.deadSouls.DeadSoulsPlugin
description: A simple tombstone system inspired by Dark Souls.
authors: [Darkyenus, Marotheit]
api-version: '1.21.3'
commands:
  souls:
    description: Lists applicable player souls.
    usage: /souls
    # Internal sub-commands:
    # /souls page <number> Shows the provided souls page in the soul list.
    # /souls release <id> Releases the provided soul.
    # /souls teleport <id> Teleports the player to the provided soul.
permissions:
  deadsouls.souls.spawn:
    description: Allows the player to spawn a soul upon death.
    default: true
  deadsouls.souls.save.items:
    description: Allows the soul to store the player's items when it is spawned.
    default: true
  deadsouls.souls.save.experience:
    description: Allows the soul to store a portion of the player's experience when it is spawned.
    default: true
  deadsouls.souls.list:
    description: Lists applicable player souls when using the /souls command.
    default: true
  deadsouls.souls.release:
    description: Allows the player to release their soul.
    default: true
  deadsouls.souls.spectator:
    description: Allows the player to see all souls in the world if they are set to the Spectator gamemode.
    default: true
  deadsouls.souls.coordinates:
    description: Displays the location of each applicable soul when using the /souls command. This will also display the location of the soul upon death.
    default: false
  deadsouls.souls.distance:
    description: Displays the distance from each applicable soul when using the /souls command.
    default: false
  deadsouls.souls.teleport:
    description: Allows the player to teleport to their soul.
    default: false
  deadsouls.souls.list.all:
    description: Lists all player souls when using the /souls command, even those that do not belong to them.
    default: op
  deadsouls.souls.release.all:
    description: Allows the player to release any soul when using the /souls command, even those that do not belong to them.
    default: op
  deadsouls.souls.teleport.all:
    description: Allows the player to teleport to any soul when using the `/souls` command, even those that do not belong to them.
    default: op